### ISSUE TITLE
[process exited with code 1 (0x00000001)]

### ISSUE THREAD

**Issue by OriginalBritts1** [DEMON1A/GmailBruterV2#16]
Hi,

As you can tell, I am not Python programmer, any assistance with the below would be greatly appreciated. 

"Traceback (most recent call last):
  File "C:\Temp\GmailBruterV2-master\GmailBruterV2.py", line 175, in <module>
    StartShell()
  File "C:\Temp\GmailBruterV2-master\GmailBruterV2.py", line 68, in StartShell
    with open(os.path.join("data" , "Commands") ,'r') as CommandsFile:
FileNotFoundError: [Errno 2] No such file or directory: 'data\\Commands'

[process exited with code 1 (0x00000001)]"

Thanks

Britts

**Comment by DEMON1A** [comment]
Can you please provide the command you used to run the tool along with your os type and the current path you ran the program from so I can check if this's a global issue or it happened from something wrong you did

**Comment by hyeeanoncod3r** [comment]
> Can you please provide the command you used to run the tool along with your os type and the current path you ran the program from so I can check if this's a global issue or it happened from something wrong you did

Same question
